// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQvl3VEovEtq6njac_dzVV63YFSXyfLss',
    appId: '1:455262020628:web:06bdecf0f0f34158993301',
    messagingSenderId: '455262020628',
    projectId: 'myfirst-ever-flutter-project',
    authDomain: 'myfirst-ever-flutter-project.firebaseapp.com',
    storageBucket: 'myfirst-ever-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoaE_zNs_NM2ta0P2wtPE3yCJV7Ldb_50',
    appId: '1:455262020628:android:f27aab9f57f88497993301',
    messagingSenderId: '455262020628',
    projectId: 'myfirst-ever-flutter-project',
    storageBucket: 'myfirst-ever-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1A82rWX_v8193fl3zkmg2LuL31l71E4',
    appId: '1:455262020628:ios:89b3335fa6a20043993301',
    messagingSenderId: '455262020628',
    projectId: 'myfirst-ever-flutter-project',
    storageBucket: 'myfirst-ever-flutter-project.appspot.com',
    iosClientId: '455262020628-f01otddkm4dmilr2fscois1ouq3eeei3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn1A82rWX_v8193fl3zkmg2LuL31l71E4',
    appId: '1:455262020628:ios:89b3335fa6a20043993301',
    messagingSenderId: '455262020628',
    projectId: 'myfirst-ever-flutter-project',
    storageBucket: 'myfirst-ever-flutter-project.appspot.com',
    iosClientId: '455262020628-f01otddkm4dmilr2fscois1ouq3eeei3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );
}
